### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Blizzard-liu** [NGUWQ/Love#1]
D:\temp\pythontest\venv\Scripts\python.exe D:/temp/pythontest/love/love.py
Traceback (most recent call last):
  File "D:\temp\pythontest\venv\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "D:\Program Files (x86)\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files (x86)\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/temp/pythontest/love/love.py", line 141, in <module>
    main()
  File "D:/temp/pythontest/love/love.py", line 127, in main
    crawl_Love_words()
  File "D:/temp/pythontest/love/love.py", line 28, in crawl_Love_words
    browser = webdriver.Chrome()
  File "D:\temp\pythontest\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "D:\temp\pythontest\venv\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Blizzard-liu** [comment]
新手小白
