### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Blizzard-liu** [NGUWQ/Love#2]
正在抓取情话...
情话抓取完成
图片已存在
@819416a4227c2e1aba49b784e029b964d033e455e314db889e0ad0f862e9fe37
['1.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg', '14.jpg', '15.jpg', '16.jpg', '17.jpg', '18.jpg', '19.jpg', '2.jpg', '20.jpg', '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg', '26.jpg', '27.jpg', '28.jpg', '29.jpg', '3.jpg', '30.jpg', '31.jpg', '32.jpg', '33.jpg', '34.jpg', '35.jpg', '36.jpg', '37.jpg', '38.jpg', '39.jpg', '4.jpg', '40.jpg', '41.jpg', '42.jpg', '43.jpg', '44.jpg', '45.jpg', '46.jpg', '47.jpg', '48.jpg', '49.jpg', '5.jpg', '50.jpg', '51.jpg', '52.jpg', '53.jpg', '54.jpg', '55.jpg', '56.jpg', '57.jpg', '58.jpg', '6.jpg', '7.jpg', '8.jpg', '9.jpg']
Traceback (most recent call last):
  File "D:/temp/pythontest/love/love.py", line 141, in <module>
    main()
  File "D:/temp/pythontest/love/love.py", line 133, in main
    send_news()
  File "D:/temp/pythontest/love/love.py", line 114, in send_news
    file = files[Wordsnumber]
IndexError: list index out of range

**Comment by Blizzard-liu** [comment]
第一次运行的时候报错
Traceback (most recent call last):
  File "D:/temp/pythontest/love/love.py", line 141, in <module>
    main()
  File "D:/temp/pythontest/love/love.py", line 133, in main
    send_news()
  File "D:/temp/pythontest/love/love.py", line 96, in send_news
    with open(file_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'love_word.txt'
